"""src/cuda/selfattn_recipes.h from selfattn_recipe_probe's output (results/selfattn_recipe_l40s.txt): for every t 1..448,
the arithmetic cuBLAS runs for one window's self-attention scores and output (100 entries, the slots' stride) on the
L40S with cuBLAS 12.9.2, one per t from the fewest recipes that cover them all (any recipe that matched t gives the
same bits there).
usage: python gen_selfattn_recipes.py [probe output] [header]"""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "results", "selfattn_recipe_l40s.txt")
dst = sys.argv[2] if len(sys.argv) > 2 else os.path.join(HERE, "..", "..", "..", "src", "cuda", "selfattn_recipes.h")
T_MAX = 448

matches, section = {"scores": {}, "output": {}}, None
for line in open(src, encoding="utf-8"):
    if line.startswith("scores by t"):
        section = "scores"
    elif line.startswith("output by t"):
        section = "output"
    elif section and (m := re.match(r"\s+t\s+(\d+)-\s*(\d+): (.*)", line)):
        for t in range(int(m.group(1)), int(m.group(2)) + 1):
            matches[section][t] = set(m.group(3).split())


def cover(section):
    """The fewest recipes matching every t (greedy), then each t's first of them."""
    left, chosen = set(range(1, T_MAX + 1)), []
    if any(matches[section].get(t, {"NONE"}) == {"NONE"} for t in left):
        sys.exit(f"{section}: a t without a matching recipe")
    while left:
        counts = {}
        for t in left:
            for c in matches[section][t]:
                counts[c] = counts.get(c, 0) + 1
        best = max(sorted(counts), key=counts.get)
        chosen.append(best)
        left = {t for t in left if best not in matches[section][t]}
    return chosen, [next(c for c in chosen if c in matches[section][t]) for t in range(1, T_MAX + 1)]


def recipe(name):
    """(kind, partials, vector, contiguous, tree): kind 0 partials, 1 an mma chain over 16-groups."""
    if name == "M":
        return (1, 0, 0, 0, 0)
    m = re.fullmatch(r"T(\d+)(?:w(\d+)|(c))([dno])", name)
    if not m:
        sys.exit(f"no recipe for {name}")
    return (0, int(m.group(1)), int(m.group(2) or 1), 1 if m.group(3) else 0, "odn".index(m.group(4)))


lines = []
for section in ("scores", "output"):
    names, per_t = cover(section)
    lines.append(f"    // {section}: " + ", ".join(names))
    lines.append(f"    constexpr SelfAttnRecipe selfattn_{section}_recipes[] = {{")
    lines += [f"      {{{', '.join(map(str, recipe(n)))}}},   // {n}" for n in names]
    lines.append("    };")
    codes = [names.index(n) for n in per_t]
    lines.append(f"    constexpr unsigned char selfattn_{section}_recipe_of_t[{T_MAX + 1}] = {{0,")
    lines += ["      " + ", ".join(str(c) for c in codes[i:i + 32]) + "," for i in range(0, T_MAX, 32)]
    lines.append("    };")

header = f"""#pragma once

// Generated by tools/turing/kernels/gen_selfattn_recipes.py from results/selfattn_recipe_l40s.txt (selfattn_recipe_probe
// on the L40S, cuBLAS 12.9.2): the arithmetic cuBLAS gives one window's self-attention products (5 beams x 20 heads,
// the slots' stride) at each t, for slot_attention.cu. Do not edit: run the generator.

namespace ctranslate2 {{
  namespace cuda {{

    // kind 0: `partials` sums, each over the elements (r + partials j) vector + u (vector consecutive elements a turn),
    // or, contiguous, over one chunk of ceil(n / partials); combined by tree 1 (s_r += s_(r + T/2) .. s_r += s_(r+1)),
    // tree 2 (from the neighbours) or in order (tree 0). kind 1: an mma.sync m16n8k16 chain over 16-groups.
    struct SelfAttnRecipe {{
      int kind, partials, vector, contiguous, tree;
    }};

{chr(10).join(lines)}

  }}
}}
"""
open(dst, "w", encoding="utf-8", newline="\n").write(header)
print(f"wrote {dst}")
